version: 2
jobs:
  static_testing:
    docker:
      - image: circleci/php:7.1-apache-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: git clone git@github.com:SimpleUpdates/ThemeTesting.git ../ThemeTesting
      - run: bash ../ThemeTesting/test-theme.sh .
  headless_testing:
    docker:
      - image: simpleupdates/themebrowsertesting:latest
        entrypoint: bash
    working_directory: /theme
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: /app/app.php /theme
      - store_artifacts:
          path: /app/build
      - run: /app/comment.js
workflows:
  version: 2
  static_and_headless:
    jobs:
      - static_testing
      - headless_testing